Dev/refactor prediction input
StefH/Replicate.Net pull request #13
Opened 2023-06-23 03:06 UTC by vin-spiegel

I think there is no interface about 'PredictionInput' to use varient inputs.
I did
- Added 'IPredictionInput'
- Refactor 'PredictionInput' to 'DefaultPredictionInput'
- Added NegativePrompt in DefaultPredictionInput

2023-06-23 06:37 UTC, StefH commented
@vin-spiegel 
Thank you.

I'll take a look.

2023-06-23 14:02 UTC, StefH commented on examples/Replicate.Net.Common/Example/Client/IExampleApi.cs
> +    Task<Prediction> CreatePredictionAsync([Body] DefaultPredictionInput input, CancellationToken cancellationToken = default);
Should this be the interface?

2023-06-23 14:05 UTC, StefH requested changes

2023-06-23 14:05 UTC, StefH commented on examples/Replicate.Net.Common/Example/Client/IExampleApiExtensions.cs
> +    public static async Task<Prediction> CreatePredictionAndWaitOnResultAsync(this IExampleApi api, DefaultPredictionInput input, int timeoutInSeconds = 5 * 60, CancellationToken cancellationToken =
Should this be the interface?

2023-06-23 14:05 UTC, StefH commented on src/Replicate.Net/Models/DefaultPredictionInput.cs
>  /// The model's input.
The default model's input.

2023-06-23 14:05 UTC, StefH commented on src/Replicate.Net/Interop/IPredictionInput.cs
> +
Add summary:
```
/// <summary>
/// The model's input.
/// </summary>
```

2023-06-23 14:05 UTC, StefH commented on src/Replicate.Net/Interop/IPredictionInput.cs
> +namespace Replicate.Net.Interop;
Rename this to `Replicate.Net.Interfaces`

2023-06-24 06:13 UTC, vin-spiegel commented on examples/Replicate.Net.Common/Example/Client/IExampleApi.cs
> +    Task<Prediction> CreatePredictionAsync([Body] DefaultPredictionInput input, CancellationToken cancellationToken = default);
Oh yes. this should be this interface

2023-06-24 06:34 UTC, closed without merging